Repository AY2425S2-CS2113-W11-4/tp, pull requests merged in 2025-04, with the labels that each got.

#47 Add Local Date and Time, implement filter-date command for Expenses
  src/main/java/seedu/tripbuddy/command/Parser.java
  src/main/java/seedu/tripbuddy/dataclass/Expense.java
  src/main/java/seedu/tripbuddy/exception/ExceptionHandler.java
  src/main/java/seedu/tripbuddy/framework/CommandHandler.java
  src/main/java/seedu/tripbuddy/framework/ExpenseManager.java
  src/test/java/seedu/tripbuddy/framework/ExpenseManagerTest.java
Labels: priority.Low

#52 Implement JSON FileHandler Class
  src/main/java/seedu/tripbuddy/dataclass/Expense.java
  src/main/java/seedu/tripbuddy/framework/ExpenseManager.java
  src/main/java/seedu/tripbuddy/storage/FileHandler.java
Labels: type.Task

#61 Added some JUnit Test Code missing
  src/test/java/seedu/tripbuddy/command/CommandTest.java
  src/test/java/seedu/tripbuddy/framework/CommandHandlerTest.java
  src/test/java/seedu/tripbuddy/framework/ExpenseManagerTest.java
  src/test/java/seedu/tripbuddy/framework/InputHandlerTest.java
Labels: type.Task

#68 Direct logging info to file
  .gitignore
  docs/UserGuide.md
  src/main/java/seedu/tripbuddy/TripBuddy.java
  src/main/java/seedu/tripbuddy/command/Parser.java
  src/main/java/seedu/tripbuddy/framework/CommandHandler.java
  src/main/java/seedu/tripbuddy/storage/DataHandler.java
  src/main/java/seedu/tripbuddy/storage/FileHandler.java
Labels: priority.High
